config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'kittens#index'
  resources :kittens

  namespace :api, defaults: { format: :json } do
    get '/kittens', to: 'kittens#index'
    get '/kitten/:id', to: 'kittens#show'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { minimum: 5 }
  validates :age, presence: true
  validates :softness, presence: true
  validates :cuteness, presence: true
end

app/controllers/api/kittens_controller.rb
class Api::KittensController < ApplicationController

  def index
    @kittens = Kitten.all
  end

  def show
    @kitten = Kitten.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  def index
    @kittens = Kitten.all
  end

  def show
  end

  def new
    @kitten = Kitten.new
  end

  def edit
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to @kitten, notice: 'Kitten was successfully created.'
    else
      render :new
    end
  end

  def update
    if @kitten.update(kitten_params)
      redirect_to @kitten, notice: 'Kitten was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @kitten.destroy
    redirect_to kittens_url, notice: 'Kitten was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitten
      @kitten = Kitten.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kitten_params
      params.require(:kitten).permit(:name, :age, :softness, :cuteness)
    end
end

app/views/kittens/_flash.html.erb
<% if !flash[:notice].nil? %>
  <br />
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <p class="text-center"><%= notice %></p>
  </div>
<% end %>
<% if !flash[:alert].nil? %>
  <br />
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <p class="text-center"><%= alert %></p>
  </div>
<% end %>

app/views/kittens/_form.html.erb
<%= form_for kitten do |form| %>
  <%= render 'form_errors', kitten: kitten %>
  <div class="form_group">
    <%= form.label :name, "Name: " %><br />
    <%= form.text_field :name, class: "form-control" %><br />
  </div>

  <div class="form_group">
    <%= form.label :age, "Age: " %><br />
    <%= form.text_field :age, class: "form-control" %><br />
  </div>

  <div class="form_group">
    <%= form.label :softness, "Softness: " %><br />
    <%= form.text_field :softness, class: "form-control" %><br />
  </div>

  <div class="form_group">
    <%= form.label :cuteness, "Cuteness: " %><br />
    <%= form.text_field :cuteness, class: "form-control" %><br />
  </div>

  <%= form.submit btn_text, class: "btn btn-default btn-block"%>
<% end %>

app/views/kittens/_form_errors.html.erb
<% if kitten.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@kitten.errors.count, "error") %> prohibited this kitten from being saved:</h2>
    <ul>
    <% kitten.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h1 class="text-center">Editing Kitten</h1>

<%= render 'form', kitten: @kitten, btn_text: "Update kitten" %>

<br />

<%= link_to 'Show', @kitten, class: "btn btn-default" %>
<%= link_to 'Back', kittens_path, class: "btn btn-default" %>

app/views/kittens/index.html.erb
<h1 class="text-center">Kittens</h1>

<table class="table table-striped text-center">
  <thead>
    <tr>
      <th class="text-center">ID</th>
      <th class="text-center">Name</th>
      <th class="text-center">Age</th>
      <th class="text-center">Cuteness</th>
      <th class="text-center">Softness</th>
      <th class="text-center">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @kittens.each do |kitten| %>
      <tr>
        <td><%= kitten.id %></td>
        <td><%= kitten.name %></td>
        <td><%= kitten.age %></td>
        <td><%= kitten.softness %></td>
        <td><%= kitten.cuteness %></td>
        <td>
          <%= link_to 'Show', kitten %>
          <%= link_to 'Edit', edit_kitten_path(kitten) %>
          <%= link_to 'Delete', kitten, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Kitten', new_kitten_path, class: "btn btn-default btn-block" %>
<br />

app/views/kittens/new.html.erb
<h1 class="text-center">New Kitten</h1>
<%= render 'form', kitten: @kitten, btn_text: "Create kitten!" %>
<br />
<%= link_to 'Back', kittens_path, class: "btn btn-default btn-block" %>

app/views/kittens/show.html.erb
<h1>Kitten: <%= @kitten.id %></h1>
<ul>
  <li>Name: <%= @kitten.name %></li>
  <li>Age: <%= @kitten.age %></li>
  <li>Softness: <%= @kitten.softness %></li>
  <li>Cuteness: <%= @kitten.cuteness %></li>
</ul>
<%= link_to 'Edit', edit_kitten_path(@kitten), class: "btn btn-default" %>
<%= link_to 'Back', kittens_path, class: "btn btn-default" %>
<%= link_to 'Delete', kitten_path(@kitten), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinSimpleKittensApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'flash' %>
      <%= yield %>
    </div>
  </body>
</html>